package com.example.traductorsenas

val allWordsRoutes = listOf(
    // EDUCACIÓN
    "Biblioteca" to "bibliotecaScreen",
    "Clase" to "claseScreen",
    "Cuaderno" to "cuadernoScreen",
    "Diploma" to "diplomaScreen",
    "Escuela" to "escuelaScreen",
    "Estudiante" to "estudianteScreen",
    "Examen" to "examenScreen",
    "Graduación" to "graduacionScreen",
    "Inglés" to "inglesScreen",
    "Libro" to "libroScreen",
    "Licenciatura" to "licenciaturaScreen",
    "Pizarrón" to "pizarronScreen",
    "Preparatoria" to "preparatoriaScreen",
    "Primaria" to "primariaScreen",
    "Secundaria" to "secundariaScreen",
    "Universidad" to "universidadScreen",

    // FAMILIA
    "Abuela" to "abuelaScreen",
    "Abuelo" to "abueloScreen",
    "Bebé" to "bebeScreen",
    "Esposa" to "esposaScreen",
    "Esposo" to "esposoScreen",
    "Hermana" to "hermanaScreen",
    "Hermano" to "hermanoScreen",
    "Hija" to "hijaScreen",
    "Hijo" to "hijoScreen",
    "Mamá" to "mamaScreen",
    "Nieta" to "nietaScreen",
    "Nieto" to "nietoScreen",
    "Niña" to "ninaScreen",
    "Niño" to "ninoScreen",
    "Papá" to "papaScreen",
    "Prima" to "primaScreen",
    "Primo" to "primoScreen",
    "Sobrina" to "sobrinaScreen",
    "Sobrino" to "sobrinoScreen",
    "Tía" to "tiaScreen",
    "Tío" to "tioScreen",

    // PROFESIONES
    "Chef" to "chefScreen",
    "Médico" to "medicoScreen",
    "Policía" to "policiaScreen",
    "Profesor" to "profesorScreen",

    // PRONOMBRES
    "Él" to "elScreen",
    "Ella" to "ellaScreen",
    "Mío" to "mioScreen",
    "Nosotros" to "nosotrosScreen",
    "Nuestro" to "nuestroScreen",
    "Suyo" to "suyoScreen",
    "Tú" to "tuScreen",
    "Tuyo" to "tuyoScreen",
    "Ustedes" to "ustedesScreen",
    "Yo" to "yoScreen",

    // PROTECCIÓN CIVIL
    "Emergencia" to "emergenciaScreen",
    "Evacuación" to "evacuacionScreen",
    "Peligro" to "peligroScreen",
    "Prevención" to "prevencionScreen",
    "Riesgo" to "riesgoScreen",
    "Seguro" to "seguroScreen",

    // NÚMEROS
    "Uno" to "unoScreen",
    "Dos" to "dosScreen",
    "Tres" to "tresScreen",
    "Cuatro" to "cuatroScreen",
    "Cinco" to "cincoScreen",
    "Seis" to "seisScreen",
    "Siete" to "sieteScreen",
    "Ocho" to "ochoScreen",
    "Nueve" to "nueveScreen",
    "Diez" to "diezScreen",

    // SALUD
    "Asco" to "ascoScreen",
    "Cansancio" to "cansancioScreen",
    "Dolor" to "dolorScreen",
    "Enfermedad" to "enfermedadScreen",
    "Medicamento" to "medicamentoScreen",
    "Nada" to "nadaScreen",
    "Poco" to "pocoScreen",

    // EXPRESIONES
    "¿Cómo estás?" to "comoestasScreen",
    "¿Cómo te llamas?" to "comotellamasScreen",
    "Disculpa" to "disculpaScreen",
    "Por favor" to "porfavorScreen",

    // SALUDOS
    "Adiós" to "adiosScreen",
    "Bienvenido" to "bienvenidoScreen",
    "Buenas noches" to "buenasnochesScreen",
    "Buenas tardes" to "buenastardesScreen",
    "Buenos días" to "buenosdiasScreen",
    "Gracias" to "graciasScreen",
    "Hola" to "holaScreen",
    "Mucho gusto" to "muchogustoScreen",

    // TEMPORALIDAD
    "Ahora" to "ahoraScreen",
    "Ahorita" to "ahoritaScreen",
    "Año" to "anoScreen",
    "Ayer" to "ayerScreen",
    "Día" to "diaScreen",
    "Hasta mañana" to "hastamananaScreen",
    "Hoy" to "hoyScreen",
    "Mañana" to "mananaScreen",
    "Mes" to "mesScreen",
    "Semana" to "semanaScreen",

    // VERBOS
    "Abrir" to "abrirScreen",
    "Aceptar" to "aceptarScreen",
    "Amar" to "amarScreen",
    "Ayudar" to "ayudarScreen",
    "Buscar" to "buscarScreen",
    "Cerrar" to "cerrarScreen",
    "Comer" to "comerScreen",
    "Conocer" to "conocerScreen",
    "Descubrir" to "descubrirScreen",
    "Dormir" to "dormirScreen",
    "Estudiar" to "estudiarScreen",
    "Hablar" to "hablarScreen",
    "Ir" to "irScreen",
    "Jugar" to "jugarScreen",
    "Leer" to "leerScreen",
    "Querer" to "quererScreen",
    "Saber" to "saberScreen",
    "Ver" to "verScreen",
    "Vivir" to "vivirScreen"
)
